config: misc/espnet_configs/hubert/train_hubert_ll60k_conformer_mtl_discrete_continuous_hmtldc.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: misc
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: 0
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 50
patience: 10
val_scheduler_criterion:
- valid
- ccc
early_stopping_criterion:
- valid
- ccc
- max
best_model_criterion:
-   - valid
    - ccc
    - max
-   - valid
    - acc
    - max
keep_nbest_models: 10
nbest_averaging_interval: 0
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: 1000
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: true
wandb_project: multilabel-emorec
wandb_id: null
wandb_entity: cmu-mlsp-emo
wandb_name: msppodcast_continuous_discrete_hmtl_dc
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 20
valid_batch_size: null
batch_bins: 21000
valid_batch_bins: null
train_shape_file:
- exp/er_stats_msp_hubert/train/speech_shape
valid_shape_file:
- exp/er_stats_msp_hubert/valid/speech_shape
batch_type: length
valid_batch_type: null
fold_length:
- 800
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/extracted/train/feats.scp
    - speech
    - kaldi_ark
-   - dump/extracted/train/text
    - emotion
    - text
-   - dump/extracted/train/emotion_cts
    - emotion_cts
    - text_float
valid_data_path_and_name_and_type:
-   - dump/extracted/valid/feats.scp
    - speech
    - kaldi_ark
-   - dump/extracted/valid/text
    - emotion
    - text
-   - dump/extracted/valid/emotion_cts
    - emotion_cts
    - text_float
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
paramgroups: null
paramlrs: null
optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000
token_list:
- <neu>
- <sad>
- <ang>
- <hap>
- <dis>
init: null
input_size: 1024
use_preprocessor: true
token_type: word
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_large_ll60k
    download_dir: ./hub
    multilayer_feature: true
    fs: 16k
specaug: null
specaug_conf: {}
normalize: null
normalize_conf: {}
model: espnet
model_conf:
    lsm_weight: 0.15
    extract_feats_in_collect_stats: false
preencoder: linear
preencoder_conf:
    input_size: 1024
    output_size: 80
encoder: conformer
encoder_conf:
    output_size: 64
    attention_heads: 8
    linear_units: 64
    num_blocks: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: linear
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31
decoder: hmtl_decoder_dc
decoder_conf:
    pool_type: att
    dropout_rate: 0.1
    decoder_style: discrete,continuous
    discrete_pool_style: joint
    continuous_pool_style: independent
    discrete_continuous_pool_style: independent
    continuous_dim_size: 3
    continuous_embedding_dim: 32
    discrete_embedding_dim: 32
required:
- output_dir
- token_list
version: '202209'
distributed: false
